# Generated by Django 4.2.7 on 2023-11-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('member', 'member'), ('moderator', 'moderator')], default='member', verbose_name='роль'),
        ),
    ]
