# Generated by Django 4.2.7 on 2023-11-19 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_service', '0003_alter_payment_payment_amount_and_more'),
        ('users', '0002_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=150, verbose_name='страна'),
        ),
        migrations.CreateModel(
            name='UserSubscriptionUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='статус подписки')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='lms_service.course', to_field='name', verbose_name='курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='пользователь')),
            ],
        ),
    ]
