# Generated by Django 4.2.7 on 2023-12-08 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateField(default=datetime.datetime(2023, 12, 8, 17, 56, 41, 601010), verbose_name='Дата последнего посещения'),
        ),
    ]
