# Generated by Django 4.2.7 on 2023-12-08 14:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateField(default=datetime.datetime(2023, 12, 8, 17, 57, 46, 324088), verbose_name='Дата последнего посещения'),
        ),
        migrations.AlterField(
            model_name='usersubscriptionupdates',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='пользователь'),
        ),
    ]
