# Generated by Django 4.2.7 on 2023-12-24 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateField(default=datetime.datetime(2023, 12, 24, 23, 42, 54, 77768), verbose_name='Дата последнего посещения'),
        ),
    ]
