# Generated by Django 4.2.7 on 2023-11-12 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название курса')),
                ('img', models.ImageField(default=None, upload_to='media/', verbose_name='Картинка')),
                ('description', models.TextField(max_length=500, verbose_name='Описание курса')),
                ('lessons_count', models.IntegerField(default=0, verbose_name='количество уроков в курсе')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название урока')),
                ('img', models.ImageField(default=None, upload_to='media/', verbose_name='Картинка')),
                ('description', models.TextField(max_length=500, verbose_name='Описание урока')),
                ('link', models.URLField(verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='lms_service.course', to_field='name', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(verbose_name='дата оплаты')),
                ('payment_amount', models.IntegerField(verbose_name='сумма оплаты')),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('transfer', 'transfer to the account')], default='transfer to the account', verbose_name='способ оплаты')),
                ('paid_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_service.course', to_field='name', verbose_name='оплаченный курс')),
                ('paid_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_service.lesson', to_field='name', verbose_name='оплаченный урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='пользователь')),
            ],
        ),
    ]
