# Generated by Django 4.2.7 on 2023-11-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_service', '0002_course_user_lesson_user_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.PositiveIntegerField(verbose_name='сумма оплаты'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('paid_course__isnull', False), ('paid_lesson__isnull', False)), name='course_lesson_not_null'),
        ),
    ]
