# Generated by Django 4.2.7 on 2023-11-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_service', '0003_alter_payment_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='статус платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_id',
            field=models.CharField(default=None, verbose_name='id платежа stripe'),
        ),
    ]
