# Generated by Django 4.2.7 on 2023-11-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_service', '0004_payment_is_confirmed_payment_pay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_id',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='id платежа stripe'),
        ),
    ]
