# Generated by Django 4.2.7 on 2023-12-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_service', '0006_remove_payment_course_lesson_not_null_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='course_lesson_not_null',
        ),
    ]
