# Generated by Django 4.2.7 on 2023-12-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_service', '0007_remove_payment_course_lesson_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='lms_service.course', to_field='name', verbose_name='курс'),
        ),
    ]
